name : first workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name : list and readfiles
        run: |
          echo "welcome to github actions"
          ls -ltra
          cat README.md
      
      - name: Generate a ASCII Artwork
        run: cowsay "Hello, World!" >> output.txt