name :  Running a custom function

on : push

jobs:
  run-fun:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: List files
          run: ls -ltra
  
        - name: Run Python script
          run: python3 -c "from main import run; run()"