name :  Running a custom function

on : push

jobs:
  run-fun:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
  
        - name: List files
          run: ls -ltra
  