name : multiple jobs workflow

on: push

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name : install cowsay
        run: sudo apt-get install -y cowsay
    
      - name : read files
        run: |
            cowsay "Hello, World!" > output.txt
            echo " printing is done"

      - name : upload output
        uses: actions/upload-artifact@v4
        with : 
            name: output
            path : output.txt


  second-job:
    runs-on: ubuntu-latest
    needs: first-job
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name : download output text file
        uses: actions/download-artifact@v4
        with : 
            name: output
              
      - name : test file exist
        run: grep -i "outpurt.txt" output.txt || echo "output.txt not found"
              
  third-job:
    runs-on : ubuntu-latest
    needs: [first-job, second-job]
    steps:        
      - name: print message
        run: echo "All jobs completed successfully!"