name: Run PR Review Agent

on:
  pull_request:
    types: [opened, synchronize]  # Trigger on PR open or update

jobs:
  run-fun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for diffing

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Get code diff
        id: diff
        run: |
          echo "Getting PR diff..."
          git fetch origin main
          git diff origin/main...HEAD > pr_diff.txt
          cat pr_diff.txt

      - name: Run PR review agent
        run: python3 main.py pr_diff.txt
